# Generated by Django 2.2.6 on 2019-12-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_othercourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingcourse',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othercourse',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100),
            preserve_default=False,
        ),
    ]
